### ISSUE TITLE
Can the border be applied to all windows?

### ISSUE THREAD

**Issue by danielbjanes** [deter0/xborder#41] opened 2022-10-01 01:52 UTC
Title, I wasn't able to find any options or docs on having the window applied to all window on the desktop. For some context I am using only I3 as a window manager without a desktop environment which maybe is causing this to happen if it not intended. Thanks!,

**Comment by deter0** [comment] 2022-10-04 13:54
The border is not supposed to apply to all windows, that feature has not been implemented

**Comment by deter0** [comment] 2022-10-07 22:11
Duplicate of #16

**Closed by deter0** 2022-10-07 22:11 UTC
